# Importando bibliotecas e documentos

In [23]:
import pandas as pd
import numpy as np

In [24]:
codigo_familia_descricao = pd.read_excel('dim_familia_produtos.xlsx')
codigo_descricoa_familia_preco_custo_produtos = pd.read_excel('dim_produtos.xlsx')
codigo_vendedor = pd.read_excel('dim_vendedor.xlsx')
vendas_contrato_data_codproduto_filial_quant_total_desconto_codvendedor_codcliente = pd.read_excel('fato_vendas.xlsx')

# Fazendo DataFrame principal para a analise

In [25]:
dados = pd.DataFrame(vendas_contrato_data_codproduto_filial_quant_total_desconto_codvendedor_codcliente)
dados = pd.merge(dados, codigo_descricoa_familia_preco_custo_produtos, how = 'outer')
dados = pd.merge(dados, codigo_familia_descricao, how = 'outer')
dados = pd.merge(dados, codigo_vendedor, how = 'outer')

In [26]:
dados.head()

,codigo_contrato,data_venda,codigo_produto,filial_venda,quantidade,valor_monetario_total,valor_desconto,codigo_vendedor,codigo_cliente,descricaoproduto,codigo_familia,preco_venda_unitario,custo_produto_unitario,descricaofamilia,nome_vendedor
0,2730124,2022-07-19,692300,17,1,385.0,-21.0,243,171953.0,Sustainable Movies White #855,0,479.0,255.89,Movies,Kelly Poynter
1,2803459,2022-10-27,692300,17,1,439.0,0.0,243,810587.0,Sustainable Movies White #855,0,479.0,255.89,Movies,Kelly Poynter
2,2669860,2022-05-05,2220400,17,1,224.0,-12.0,243,68945.0,Delicious Movies Magenta #908,0,256.5,137.74,Movies,Kelly Poynter
3,2654958,2022-04-14,2220500,17,1,230.0,0.0,243,563618.0,Beautiful Movies Pink #884,0,256.5,137.74,Movies,Kelly Poynter
4,2580904,2022-01-20,2220600,17,1,207.0,0.0,243,267795.0,Durable Movies Blue #180,0,256.5,137.74,Movies,Kelly Poynter

In [27]:
dados.rename(columns={"codigo_contrato": "Contrato","data_venda":"Data"})

,Contrato,Data,codigo_produto,filial_venda,quantidade,valor_monetario_total,valor_desconto,codigo_vendedor,codigo_cliente,descricaoproduto,codigo_familia,preco_venda_unitario,custo_produto_unitario,descricaofamilia,nome_vendedor
0,2730124,2022-07-19,692300,17,1,385.00,-21.0,243,171953.0,Sustainable Movies White #855,0,479.0,255.89,Movies,Kelly Poynter
1,2803459,2022-10-27,692300,17,1,439.00,0.0,243,810587.0,Sustainable Movies White #855,0,479.0,255.89,Movies,Kelly Poynter
2,2669860,2022-05-05,2220400,17,1,224.00,-12.0,243,68945.0,Delicious Movies Magenta #908,0,256.5,137.74,Movies,Kelly Poynter
3,2654958,2022-04-14,2220500,17,1,230.00,0.0,243,563618.0,Beautiful Movies Pink #884,0,256.5,137.74,Movies,Kelly Poynter
4,2580904,2022-01-20,2220600,17,1,207.00,0.0,243,267795.0,Durable Movies Blue #180,0,256.5,137.74,Movies,Kelly Poynter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196153,2697850,2022-06-08,2719200,1,1,133.00,0.0,645,788396.0,Powerful Bracelets Cyan #461,OPP,142.0,76.51,Bracelets,Sherry Jeffers
196154,2724186,2022-07-12,2719200,1,1,133.00,0.0,645,788396.0,Powerful Bracelets Cyan #461,OPP,142.0,76.51,Bracelets,Sherry Jeffers
196155,2716602,2022-07-02,2719400,1,1,151.00,0.0,645,792294.0,Comfortable Bracelets Green #130,OPP,207.0,111.55,Bracelets,Sherry Jeffers
196156,2733084,2022-07-22,2490301,1,1,1222.65,0.0,645,796062.0,Fun Arts and Crafts Brown #472,ROHO,1380.0,730.00,Arts and Crafts,Sherry Jeffers
196157,2844386,2022-12-22,2434324,1,1,340.00,0.0,645,770773.0,Powerful Hardware Navy #847,SCF,358.6,156.64,Hardware,Sherry Jeffers

# Analise de dados:

In [ ]:
'''Análise de dados: 
I. Relatório de vendas ao longo do ano, por mês e por semana.
total R$, n e lucro vendas
produtos por filial, vendedor
total R$, n e lucro por vendedor, filial, produtos, familia de produtos
no ano todo, por mes e por semana

II. Indicação de cinco (5) famílias de produtos para focar nas campanhas de marketing em dezembro, apartir do histórico e tendencias de fim de ano.

III. Avaliação de desempenho de vendedores apartir da analise do número de produtos vendidos, número de clientes, ticket médio e receita e lucro gerada. 5 melhores vendedores do ano, com paração grafica geral e tratativa para melhorar as vendas dos vendedores com desempenho abaixo da média.

IV. Calculo do ticket médio por filial, Churn Rate por vendedor/filial/geral, Lifetime Value (LTV) dos Cliente individualmente e em média, Taxa de Recorrência e Margens de Lucro.'''